update database test data
kubearchive/kubearchive pull request #188
Opened 2024-07-18 08:59 UTC by mafh314

Fixes [#181](https://github.com/kubearchive/kubearchive/issues/181)

2024-07-18 10:55 UTC, maruiz93 requested changes
If we are inserting uuid from the resource, shouldn't we specify in the table DDL, that the field shouldn't be empty?

```
CREATE TABLE IF NOT EXISTS public.resource (
-               "uuid" uuid PRIMARY KEY,
+               "uuid" uuid PRIMARY KEY NOT NULL,
                "api_version" varchar NOT NULL,
```

EDIT: You are right, based on the comments you wrote, this change isn't needed at all, I'll approve the PR

2024-07-18 11:25 UTC, rh-hemartin commented on database/resource.sql
> +INSERT INTO public.resource (api_version,"cluster",cluster_uid,kind,"name","namespace",resource_version,created_ts,updated_ts,cluster_deleted_ts,"data","uuid") VALUES
Those changes are more extensive than just removing them here, I would like that we address that in another place for an easier review.

2024-07-18 14:21 UTC, ggallen commented
> If we are inserting uuid from the resource, shouldn't we specify in the table DDL, that the field shouldn't be empty?

By definition a primary key can not be NULL.  I think `PRIMARY KEY NOT NULL` might be invalid SQL.

2024-07-18 14:26 UTC, rh-hemartin commented
> > If we are inserting uuid from the resource, shouldn't we specify in the table DDL, that the field shouldn't be empty?
> 
> By definition a primary key can not be NULL. I think `PRIMARY KEY NOT NULL` might be invalid SQL.

I think its valid because it is on `main` and its currently working.

2024-07-18 14:29 UTC, ggallen commented
> > > If we are inserting uuid from the resource, shouldn't we specify in the table DDL, that the field shouldn't be empty?
> > 
> > 
> > By definition a primary key can not be NULL. I think `PRIMARY KEY NOT NULL` might be invalid SQL.
> 
> I think its valid because it is on `main` and its currently working.

Then why is there any change proposed here?

2024-07-18 14:33 UTC, rh-hemartin commented
> Then why is there any change proposed here?

Its not being proposed.  @maruiz93 added a code block that resembles a diff to ask for that change.

2024-07-18 15:01 UTC, beerparty approved these changes

2024-07-19 09:43 UTC, maruiz93 approved these changes

2024-07-22 08:02 UTC, mafh314 commented
> Edit: I think now I understand what you meant. You are both right (by definition a primary key can not be NULL) and wrong (because its a valid SQL). **We are fixing the sample resources to have a uuid because it can't be null.**
This PR is only to fix the issue that we have with the test data. I didn't apply any change to the _init_db_ script. If any change, related to the Db schema, is needed,  we can a open a new issue.

2024-07-22 08:04 UTC, rh-hemartin approved these changes

2024-07-22 08:28 UTC, merged