Change API Gin metrics package
kubearchive/kubearchive pull request #578
Opened 2024-10-23 08:34 UTC by rh-hemartin

## Which Issue(s) this Pull Request Resolves

Resolves #

## Release Note

```release-note
NONE
```

## Notes for Reviewers

2024-10-23 10:17 UTC, maruiz93 commented
Can you please develop the need of why should this change done? Maybe by linking a ticket with the proposed change?

As far as I am aware the previous package `go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin` is the "official" one and the proposed one doesn't have details on what differentiates it from the official package.

2024-10-23 10:17 UTC, maruiz93 requested changes
Can you please develop the need of why should this change done? Maybe by linking a ticket with the proposed change?

As far as I am aware the previous package `go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin` is the "official" one and the proposed one doesn't have details on what differentiates it from the official package.

2024-10-23 10:27 UTC, rh-hemartin commented
> Can you please develop the need of why should this change done? Maybe by linking a ticket with the proposed change?
> 
> As far as I am aware the previous package `go.opentelemetry.io/contrib/instrumentation/github.com/gin-gonic/gin/otelgin` is the "official" one and the proposed one doesn't have details on what differentiates it from the official package.

I added some reviewers notes to the PR.

2024-10-23 15:24 UTC, maruiz93 approved these changes

2024-10-28 10:04 UTC, rh-hemartin commented
Hey @maruiz93 and @skoved I changed something across all tests. We were using `http.NewRequest` with `nil` as body. This caused the Body of the request to be `nil`, which then made the new middleware we are introducing fail because of that. We changed all `http.NewRequest` to `httptest.NewRequest` which does not set `Body` as `nil` if `nil` is passed as body parameter.

I checked that in the real scenario, when you call the API with curl the body is not nil but an empty string. Instead of passing `strings.NewReader("")` to all `http.NewRequest` I think its better to go with the `httptest` package which already accounts for that.

Let me know what you think about this.

2024-10-28 10:28 UTC, maruiz93 approved these changes

2024-10-29 06:50 UTC, merged