Fix operator liveness and readiness probes.
kubearchive/kubearchive pull request #581
Opened 2024-10-23 22:55 UTC by ggallen

## Which Issue(s) this Pull Request Resolves

Resolves #439

## Release Note

```release-note
NONE
```

## Notes for Reviewers

2024-10-24 13:08 UTC, rh-hemartin commented
You need to remove the current health endpoint the operator runs, its on the cmd here: https://github.com/kubearchive/kubearchive/blob/main/charts/kubearchive/templates/operator/operator.yaml#L54, https://github.com/kubearchive/kubearchive/blob/main/cmd/operator/main.go#L116

2024-10-25 08:07 UTC, maruiz93 commented
> You need to remove the current health endpoint the operator runs, its on the cmd here: https://github.com/kubearchive/kubearchive/blob/main/charts/kubearchive/templates/operator/operator.yaml#L54, https://github.com/kubearchive/kubearchive/blob/main/cmd/operator/main.go#L116

Also worth noticing that the endpoints were exposed on the port 8081 [here](https://github.com/ggallen/kubearchive/blob/issue-439/cmd/operator/main.go#L68-L68) so you'll need to remove that line too.

2024-10-25 11:51 UTC, maruiz93 commented
I also have some doubts about using the validation endpoint for the liveness probe, is this a standard thing to do? I am having a hard time finding similar examples in other operators... so I don't have any specific suggestion but wanted to raise the concern in case you know better where to search

2024-10-25 11:54 UTC, maruiz93 requested changes
Also, waiting for kubearchive operator webhooks is also used in https://github.com/kubearchive/kubearchive/blob/main/integrations/logging/elasticsearch/install.sh#L32-L32 (should be commented/removed)

2024-10-25 12:41 UTC, ggallen commented
> I also have some doubts about using the validation endpoint for the liveness probe, is this a standard thing to do?

Yeah, I'm doubting it too. I'm trying to find a better solution.

2025-01-15 19:42 UTC, skoved commented
@ggallen what's going on with this PR? If you're not working on it could you close it?

2025-06-23 06:11 UTC, rh-hemartin commented
Closing, the best approach will be to open a new PR, given that this one is very old.

2025-06-23 06:11 UTC, closed without merging