Refactor errors
kubearchive/kubearchive pull request #675
Opened 2024-11-22 14:12 UTC by rh-hemartin

## Which Issue(s) this Pull Request Resolves

Resolves #536 

## Release Note

```release-note
NONE
```

## Notes for Reviewers

2024-11-26 16:04 UTC, maruiz93 requested changes
Added a little suggestion for the log in Abort.

2024-11-27 08:56 UTC, rh-hemartin commented on cmd/api/abort/abort.go
> +	slog.Error("there was a problem and we called abort.Abort", "error", err.Error(), "code", code)
I remove the reference to itself, it does not make a lot of sense now on a second thought. Adding the line number its not very helpful, as we already know where this located.

2024-11-27 09:24 UTC, maruiz93 commented on cmd/api/abort/abort.go
> +	slog.Error("there was a problem and we called abort.Abort", "error", err.Error(), "code", code)
> as we already know where this located

In my experience having the filename and the line number added to the logs are a pretty standard practice, they usually help with troubleshooting.

We (as the main developers) know where the things are in the code, but with time the code base will increase and for people that are not main developers, seeing that kind of information could help.

I think that we can explore exposing the source file in the logs, maybe we can open an issue for that.

2024-11-27 09:25 UTC, maruiz93 approved these changes

2024-11-27 14:53 UTC, ggallen approved these changes

2024-11-27 15:29 UTC, merged